### ISSUE TITLE
Rscript runtime error

### ISSUE THREAD

**Issue by abedkurdi** [Griffan/FASTQuick#9]
Hello there,
I used the dataset provided in the package to test the tool and once I tried to run the `Rscript` to generate the plots, it throws the following error:
`[1] "Usage:Rscript RPlotScript.R <output_prefix> <SVDPrefix> <FASTQuickInstallDir>"
Warning message:
In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
Warning message:
In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
Error in pivot:1 : argument of length 0
Calls: findBump
Execution halted`

I used the following command to invoke the `Rscript`:
`Rscript RPlotScript.R test_out hapmap_3.3.b37.dat ${FASTQuick}`

note that I have put `hapmap_3.3.b37.dat` files in the same directory as output files.
Thank you in advance.

**Comment by Griffan** [comment]
Hi, thanks for the feedback! 
The test_out files generated in the example directory are just a very tiny file for the compilation sanity check. These files will not produce a meaningful result due to too little information in the example fastq files(1000 reads). These R errors will go away if you test the plot script on a larger dataset(for example, the HG00553 fastq files listed in the readme).

It's strongly recommended to follow the #quick start# in the readme to use the FASTQuick.sh one-stop pipeline to generate the user-friendly QC report. 

Please let me know if you get rid of these errors.

**Comment by abedkurdi** [comment]
I appreciate your advice, Thank you very much
